# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='right_or_wrong',
        ),
        migrations.AddField(
            model_name='bet',
            name='correct_choice',
            field=models.CharField(default='Maybe', max_length=200),
        ),
    ]
