# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet_app', '0004_auto_20170116_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
