# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet_app', '0005_choice_is_chosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='bet_number',
        ),
    ]
